In [30]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [31]:
bt1 = pd.read_csv("Q3_train_data.csv")
bvs1 = pd.read_csv("Q3_dev_data.csv")
bts1 = pd.read_csv("Q3_test_data.csv")
bps1 = np.array(pd.read_csv("Q3_pred_data.csv"))

In [32]:
model = tf.keras.Sequential([
	tf.keras.layers.InputLayer(input_shape=(5), name="InputLayer"),
	tf.keras.layers.Dense(5, activation="relu", name="HiddenLayer.1"),
	tf.keras.layers.Dropout(0.1),
	tf.keras.layers.Dense(5, activation="relu", name="HiddenLayer.2"),
  tf.keras.layers.Dropout(0.1),
  tf.keras.layers.Dense(5, activation="relu", name="HiddenLayer.3"),
	tf.keras.layers.Dense(3, activation="sigmoid", name="OutputLayer")
])
model.compile(optimizer="adam", loss="mse")
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 HiddenLayer.1 (Dense)       (None, 5)                 30        
                                                                 
 dropout_8 (Dropout)         (None, 5)                 0         
                                                                 
 HiddenLayer.2 (Dense)       (None, 5)                 30        
                                                                 
 dropout_9 (Dropout)         (None, 5)                 0         
                                                                 
 HiddenLayer.3 (Dense)       (None, 5)                 30        
                                                                 
 OutputLayer (Dense)         (None, 3)                 18        
                                                                 
Total params: 108
Trainable params: 108
Non-trainable 

In [33]:
class LossThresholdCallback(tf.keras.callbacks.Callback):
	def __init__(self, threshold):
		super(LossThresholdCallback, self).__init__()
		self.threshold = threshold
	def on_epoch_end(self, epoch, logs=None):
		if logs['val_loss'] <= self.threshold:
			self.model.stop_training=True

print("TRAINING ML PROGRAM")
model.fit(
	x=np.array(bt1.loc[:,"X4":"X0"]),
	y=np.array(bt1.loc[:,"Y2":"Y0"]),
	validation_data=(
		np.array(bvs1.loc[:,"X4":"X0"]),
		np.array(bvs1.loc[:,"Y2":"Y0"])
	),
	batch_size=8,

	epochs=300,
	callbacks=[LossThresholdCallback(0.03)]
)

TRAINING ML PROGRAM
Epoch 1/300
2/2 [==============================] - 1s 161ms/step - loss: 0.2474 - val_loss: 0.2484
Epoch 2/300
2/2 [==============================] - 0s 33ms/step - loss: 0.2464 - val_loss: 0.2484
Epoch 3/300
2/2 [==============================] - 0s 45ms/step - loss: 0.2505 - val_loss: 0.2483
Epoch 4/300
2/2 [==============================] - 0s 34ms/step - loss: 0.2459 - val_loss: 0.2482
Epoch 5/300
2/2 [==============================] - 0s 38ms/step - loss: 0.2532 - val_loss: 0.2482
Epoch 6/300
2/2 [==============================] - 0s 33ms/step - loss: 0.2462 - val_loss: 0.2481
Epoch 7/300
2/2 [==============================] - 0s 34ms/step - loss: 0.2443 - val_loss: 0.2481
Epoch 8/300
2/2 [==============================] - 0s 51ms/step - loss: 0.2450 - val_loss: 0.2481
Epoch 9/300
2/2 [==============================] - 0s 30ms/step - loss: 0.2499 - val_loss: 0.2480
Epoch 10/300
2/2 [==============================] - 0s 32ms/step - loss: 0.2476 - val_loss: 0.248

In [34]:
print("TESTING ML PROGRAM")
model.evaluate(
	x=np.array(bts1.loc[:,"X4":"X0"]),
	y=np.array(bts1.loc[:,"Y2":"Y0"])
)

TESTING ML PROGRAM
1/1 [==============================] - 0s 23ms/step - loss: 0.2538


0.2538088858127594

In [35]:
print("PREDICTION ML PROGRAM")
predictions = model.predict(bps1)

for i in range(len(predictions)):
	print(str(bps1[i]) + " => " + str(predictions[i]) + " => " + str(np.round(predictions[i])))

PREDICTION ML PROGRAM
1/1 [==============================] - 0s 65ms/step
[0 0 1 1 1] => [0.5289383  0.8609239  0.72742915] => [1. 1. 1.]
[1 0 1 0 0] => [0.6513952 0.9184487 0.7489033] => [1. 1. 1.]
[0 1 0 1 1] => [0.5092908  0.4344824  0.42851895] => [1. 0. 0.]
